module.exports = function(app) {
    var ctrl = require('./control');
    //api
    /*
    app.route('/api/accounts')
      .get(ctrl.list_all_account);
      
    app.route('/api/account/:accountId')
      .get(ctrl.read_a_account)
      .put(ctrl.update_a_account)
      .delete(ctrl.delete_a_account)
      .post(ctrl.create_a_account);
    */
    //user
    app.route('/api/users')
      .get(ctrl.read_all_user)
    app.route('/api/user/:id')  
      .get(ctrl.read_a_user)
      .put(ctrl.update_a_user)
      .delete(ctrl.delete_a_user);
    app.route('/api/user/')
      .post(ctrl.create_a_user)
    
    //region
    app.route('/api/regions')
      .get(ctrl.read_all_region);
    app.route('/api/region/') 
      .post(ctrl.create_a_region); 
    app.route('/api/region/:id')  
      .get(ctrl.read_a_region)
      .put(ctrl.update_a_region)
      .delete(ctrl.delete_a_region);
      
    //changwat
    app.route('/api/changwats')
      .get(ctrl.read_all_changwat);
    app.route('/api/changwat/')
      .post(ctrl.create_a_changwat)
    app.route('/api/changwat/:id')  
      .get(ctrl.read_a_changwat)
      .put(ctrl.update_a_changwat)
      .delete(ctrl.delete_a_changwat);
      
    //amphoe
    app.route('/api/amphoes')
      .get(ctrl.read_all_amphoe);
    app.route('/api/amphoe/')
      .post(ctrl.create_a_amphoe)
    app.route('/api/amphoe/:id')  
      .get(ctrl.read_a_amphoe)
      .put(ctrl.update_a_amphoe)
      .delete(ctrl.delete_a_amphoe);
      
    //tambon
    app.route('/api/tambons')
      .get(ctrl.read_all_tambon);
    app.route('/api/tambon/')
      .post(ctrl.create_a_tambon)
    app.route('/api/tambon/:id')  
      .get(ctrl.read_a_tambon)
      .put(ctrl.update_a_tambon)
      .delete(ctrl.delete_a_tambon);  
    //district
    app.route('/api/districts')
      .get(ctrl.read_all_district);
    app.route('/api/district/')
      .post(ctrl.create_a_district)
      app.route('/api/district/:id')  
      .get(ctrl.read_a_district)
      .put(ctrl.update_a_district)
      .delete(ctrl.delete_a_district);
    //EnumerationArea
    app.route('/api/EAs')
      .get(ctrl.read_all_enumerationArea);
    app.route('/api/EA/')
      .post(ctrl.create_a_enumerationArea);
      app.route('/api/amphoe/:id')  
      .get(ctrl.read_a_enumerationArea)
      .put(ctrl.update_a_enumerationArea)
      .delete(ctrl.delete_a_enumerationArea);
    
    //waterCensus1
    app.route('/api/waterCensus1s')
      .get(ctrl.read_all_waterCensus1);
    app.route('/api/waterCensus1/')
      .post(ctrl.create_a_waterCensus1);
    app.route('/api/waterCensus1/:id')  
      .get(ctrl.read_a_waterCensus1)
      .put(ctrl.update_a_waterCensus1)
      .delete(ctrl.delete_a_waterCensus1);

    //building
    app.route('/api/buildings')
      .get(ctrl.read_all_building);
    app.route('/api/building/')
      .post(ctrl.create_a_building);
    app.route('/api/building/:id')  
      .get(ctrl.read_a_building)
      .put(ctrl.update_a_building)
      .delete(ctrl.delete_a_building);

    //household
    app.route('/api/households')
      .get(ctrl.read_all_household);
    app.route('/api/household/')
      .post(ctrl.create_a_household);
    app.route('/api/household/:id')  
      .get(ctrl.read_a_household)
      .put(ctrl.update_a_household)
      .delete(ctrl.delete_a_household);

    //waterCensus21
    app.route('/api/waterCensus21s')
      .get(ctrl.read_all_waterCensus21);
    app.route('/api/waterCensus21/')
      .post(ctrl.create_a_waterCensus21);
    app.route('/api/waterCensus21/:id')  
      .get(ctrl.read_a_waterCensus21)
      .put(ctrl.update_a_waterCensus21)
      .delete(ctrl.delete_a_waterCensus21);
    //wc21_1
    app.route('/api/wc21_1s')
      .get(ctrl.read_all_wc21_1);
    app.route('/api/wc21_1/')
      .post(ctrl.create_a_wc21_1);
    app.route('/api/wc21_1/:id')  
    .get(ctrl.read_a_wc21_1)
    .put(ctrl.update_a_wc21_1)
    .delete(ctrl.delete_a_wc21_1);        
    //wc21_2
    app.route('/api/wc21_2s')
      .get(ctrl.read_all_wc21_2);
    app.route('/api/wc21_2/')
      .post(ctrl.create_a_wc21_2);
    app.route('/api/wc21_2/:id')  
      .get(ctrl.read_a_wc21_2)
      .put(ctrl.update_a_wc21_2)
      .delete(ctrl.delete_a_wc21_2);    
    //wc21_3
    app.route('/api/wc21_3s')
      .get(ctrl.read_all_wc21_3);
    app.route('/api/wc21_3/')
      .post(ctrl.create_a_wc21_3);
    app.route('/api/wc21_3/:id')  
      .get(ctrl.read_a_wc21_3)
      .put(ctrl.update_a_wc21_3)
      .delete(ctrl.delete_a_wc21_3);        
    //wc21_4
    app.route('/api/wc21_4s')
      .get(ctrl.read_all_wc21_4);
    app.route('/api/wc21_4/')
      .post(ctrl.create_a_wc21_4);
    app.route('/api/wc21_4/:id')  
      .get(ctrl.read_a_wc21_4)
      .put(ctrl.update_a_wc21_4)
      .delete(ctrl.delete_a_wc21_4);         
    //wc21_5_1
    app.route('/api/wc21_5_1s')
      .get(ctrl.read_all_wc21_5_1);
    app.route('/api/wc21_5_1/')
      .post(ctrl.create_a_wc21_5_1);
    app.route('/api/wc21_5_1/:id')  
      .get(ctrl.read_a_wc21_5_1)
      .put(ctrl.update_a_wc21_5_1)
      .delete(ctrl.delete_a_wc21_5_1);    
    //wc21_5_2
    app.route('/api/wc21_5_2s')
      .get(ctrl.read_all_wc21_5_2);
    app.route('/api/wc21_5_2/')
      .post(ctrl.create_a_wc21_5_2);
    app.route('/api/wc21_5_2/:id')  
      .get(ctrl.read_a_wc21_5_2)
      .put(ctrl.update_a_wc21_5_2)
      .delete(ctrl.delete_a_wc21_5_2);  
    //wc21_5_3
    app.route('/api/wc21_5_3s')
      .get(ctrl.read_all_wc21_5_3);
    app.route('/api/wc21_5_3/')
      .post(ctrl.create_a_wc21_5_3);
    app.route('/api/wc21_5_3/:id')  
      .get(ctrl.read_a_wc21_5_3)
      .put(ctrl.update_a_wc21_5_3)
      .delete(ctrl.delete_a_wc21_5_3);
    //wc21_5_4
    app.route('/api/wc21_5_4s')
      .get(ctrl.read_all_wc21_5_4);
    app.route('/api/wc21_5_4/')
      .post(ctrl.create_a_wc21_5_4);
    app.route('/api/wc21_5_4/:id')  
      .get(ctrl.read_a_wc21_5_4)
      .put(ctrl.update_a_wc21_5_4)
      .delete(ctrl.delete_a_wc21_5_4);
    //wc21_5_5
    app.route('/api/wc21_5_5s')
      .get(ctrl.read_all_wc21_5_5);
    app.route('/api/wc21_5_5/')
      .post(ctrl.create_a_wc21_5_5);
    app.route('/api/wc21_5_5/:id')  
      .get(ctrl.read_a_wc21_5_5)
      .put(ctrl.update_a_wc21_5_5)
      .delete(ctrl.delete_a_wc21_5_5);    
    //wc21_5_6
    app.route('/api/wc21_5_6s')
      .get(ctrl.read_all_wc21_5_6);
    app.route('/api/wc21_5_6/')
      .post(ctrl.create_a_wc21_5_6);
    app.route('/api/wc21_5_6/:id')  
      .get(ctrl.read_a_wc21_5_6)
      .put(ctrl.update_a_wc21_5_6)
      .delete(ctrl.delete_a_wc21_5_6);   
    //wc21_5_7
    app.route('/api/wc21_5_7s')
      .get(ctrl.read_all_wc21_5_7);
    app.route('/api/wc21_5_7/')
      .post(ctrl.create_a_wc21_5_7);
    app.route('/api/wc21_5_7/:id')  
      .get(ctrl.read_a_wc21_5_7)
      .put(ctrl.update_a_wc21_5_7)
      .delete(ctrl.delete_a_wc21_5_7);    
    //wc21_6      
    app.route('/api/wc21_6s')
      .get(ctrl.read_all_wc21_6);
    app.route('/api/wc21_6/')
      .post(ctrl.create_a_wc21_6);
    app.route('/api/wc21_6/:id')  
      .get(ctrl.read_a_wc21_6)
      .put(ctrl.update_a_wc21_6)
      .delete(ctrl.delete_a_wc21_6);
    //rice        
    app.route('/api/rices')
      .get(ctrl.read_all_rice);
    app.route('/api/rice/')
      .post(ctrl.create_a_rice);
    app.route('/api/rice/:id')  
      .get(ctrl.read_a_rice)
      .put(ctrl.update_a_rice)
      .delete(ctrl.delete_a_rice);
    //plant        
    app.route('/api/plants')
      .get(ctrl.read_all_plant);
    app.route('/api/plant/')
      .post(ctrl.create_a_plant);
    app.route('/api/plant/:id')  
      .get(ctrl.read_a_plant)
      .put(ctrl.update_a_plant)
      .delete(ctrl.delete_a_plant);
    //rubber 
    app.route('/api/rubbers')
      .get(ctrl.read_all_rubber);
    app.route('/api/rubber/')
      .post(ctrl.create_a_rubber);
    app.route('/api/rubber/:id')  
      .get(ctrl.read_a_rubber)
      .put(ctrl.update_a_rubber)
      .delete(ctrl.delete_a_rubber);     
    //perennial    
    app.route('/api/perennials')
      .get(ctrl.read_all_perennial);
    app.route('/api/perennial/')
      .post(ctrl.create_a_perennial);
    app.route('/api/perennial/:id')  
      .get(ctrl.read_a_perennial)
      .put(ctrl.update_a_perennial)
      .delete(ctrl.delete_a_perennial);
    //vegetable
    app.route('/api/vegetables')
      .get(ctrl.read_all_vegetable);
    app.route('/api/vegetable/')
      .post(ctrl.create_a_vegetable);
    app.route('/api/vegetable/:id')  
      .get(ctrl.read_a_vegetable)
      .put(ctrl.update_a_vegetable)
      .delete(ctrl.delete_a_vegetable);   
    //garden   
    app.route('/api/gardens')
      .get(ctrl.read_all_garden);
    app.route('/api/garden/')
      .post(ctrl.create_a_garden);
    app.route('/api/garden/:id')  
      .get(ctrl.read_a_garden)
      .put(ctrl.update_a_garden)
      .delete(ctrl.delete_a_garden);
    //fish   
    app.route('/api/fishs')
      .get(ctrl.read_all_fish);
    app.route('/api/fish/')
      .post(ctrl.create_a_fish);
    app.route('/api/fish/:id')  
      .get(ctrl.read_a_fish)
      .put(ctrl.update_a_fish)
      .delete(ctrl.delete_a_fish);
    //shrimp    
    app.route('/api/shrimps')
      .get(ctrl.read_all_shrimp);
    app.route('/api/shrimp/')
      .post(ctrl.create_a_shrimp);
    app.route('/api/shrimp/:id')  
      .get(ctrl.read_a_shrimp)
      .put(ctrl.update_a_shrimp)
      .delete(ctrl.delete_a_shrimp);
    //flog
    app.route('/api/flogs')
      .get(ctrl.read_all_flog);
    app.route('/api/flog/')
      .post(ctrl.create_a_flog);
    app.route('/api/flog/:id')  
      .get(ctrl.read_a_flog)
      .put(ctrl.update_a_flog)
      .delete(ctrl.delete_a_flog);        
    //crocodile   
    app.route('/api/crocodiles')
      .get(ctrl.read_all_crocodile);
    app.route('/api/crocodile/')
      .post(ctrl.create_a_crocodile);
    app.route('/api/crocodile/:id')  
      .get(ctrl.read_a_crocodile)
      .put(ctrl.update_a_crocodile)
      .delete(ctrl.delete_a_crocodile);
    //s_turtle     
    app.route('/api/s_turtles')
      .get(ctrl.read_all_s_turtle);
    app.route('/api/s_turtle/')
      .post(ctrl.create_a_s_turtle);
    app.route('/api/s_turtle/:id')  
      .get(ctrl.read_a_s_turtle)
      .put(ctrl.update_a_s_turtle)
      .delete(ctrl.delete_a_s_turtle);
    //well       
    app.route('/api/wells')
      .get(ctrl.read_all_well);
    app.route('/api/well/')
      .post(ctrl.create_a_well);
    app.route('/api/well/:id')  
      .get(ctrl.read_a_well)
      .put(ctrl.update_a_well)
      .delete(ctrl.delete_a_well);
    //pool_size  
    app.route('/api/pool_sizes')
      .get(ctrl.read_all_pool_size);
    app.route('/api/pool_size/')
      .post(ctrl.create_a_pool_size);
    app.route('/api/pool_size/:id')  
      .get(ctrl.read_a_pool_size)
      .put(ctrl.update_a_pool_size)
      .delete(ctrl.delete_a_pool_size);
    //pool       
    app.route('/api/pools')
      .get(ctrl.read_all_pool);
    app.route('/api/pool/')
      .post(ctrl.create_a_pool);
    app.route('/api/pool/:id')  
      .get(ctrl.read_a_pool)
      .put(ctrl.update_a_pool)
      .delete(ctrl.delete_a_pool); 
    //pump   
    app.route('/api/pumps')
      .get(ctrl.read_all_pump);
    app.route('/api/pump/')
      .post(ctrl.create_a_pump);
    app.route('/api/pump/:id')  
      .get(ctrl.read_a_pump)
      .put(ctrl.update_a_pump)
      .delete(ctrl.delete_a_pump);
    //page
    app.route('/')
      .get(ctrl.getHomePage);

  };  
  